#!/usr/bin/python

# -*- coding: utf-8 -*-
import re
import sys


from dagobah.daemon.app import daemon_entrypoint

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(daemon_entrypoint())
